# Site
repository: ia/modern-resume-theme
favicon: images/cli.ico


# Content configuration version
version: 2


# Personal info
name: Ivan Zorin
title_tag: System Engineer
title: <ul><li>System Engineer</li><li>Open Source Developer</li><li>Independent Researcher</li><li>Community Manager</li><li>Fullheap Maintainer</li><li>Conference Speaker</li><ul>
#title: |
#  System Engineer
#  Open Source Developer
#  Independent Researcher
#  Community Manager
#  Fullheap Maintainer


#email: no-spam-please-no-please-no
#website: https://github.com/ia/modern-resume-theme


# Dark Mode (true/false/never)
darkmode: false


# Social links
# github_username:
# flickr_username:
# instagram_username:
# linkedin_username: ivzin


# font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
additional_links:
- title: GitHub
  icon: fab fa-github
  url: https://github.com/ia
#- title: CV
#  icon: fas fa-file-invoice
#  url: https://ia.github.io/cv
#- title: LinkedIn
#  icon: fab fa-linkedin-in
#  url: https://linkedin.com/in/ivzin
#- title: Blog
#  icon: fas fa-i-cursor
#  url: https://ia.github.io/log/
- title: HomeLab
  icon: fas fa-microchip
  url: https://h0melab.github.io


# About Section
# about_title: About Me
#?about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, friend. I'm just a regular average techie, but very curious one and this is my portfolio page.  




  My engineering related toolset:
  - natural languages: fluent in <mark>English</mark> and <mark>Russian</mark>;
  - programming languages: basics of <mark>Bash</mark>, <mark>C</mark>, <mark>C++</mark>, <mark>Python</mark>, <mark>Java</mark>;
  - operating systems: experience of tampering with <mark>GNU/Linux</mark>, <mark>OpenWrt</mark>, <mark>Android</mark>, <mark>Windows</mark>, <mark>MacOS</mark>, <mark>FreeBSD</mark>, <mark>QNX</mark>, <mark>ThreadX</mark>, <mark>ESXi</mark>;
  - server management: basic knowledge of how to deploy, configure & maintain <mark>OpenSSH</mark>, <mark>OpenVPN</mark>, <mark>Nginx</mark>, <mark>Samba</mark>, <mark>TFTP</mark>;
  - web: minimal level of <mark>HTML</mark>/<mark>CSS</mark>/<mark>JavaScript</mark> and <mark>Jekyll</mark>/<mark>Liquid</mark>/<mark>YAML</mark> to make clean, lightweight & elegant static sites;
  - testing: deep <mark>SDET</mark>/<mark>QA</mark> automation experience by developing test tools and making custom hardware stands to test & verify system software;
  - development tools: <mark>GCC</mark> and <mark>LLVM</mark> <mark>toolchains</mark> usage for cross-compilation, porting & code sanitization;
  - system skills: <mark>POSIX</mark>, network programming (<mark>BSD sockets</mark> & <mark>WinSock</mark>) and packet routing, <mark>storage</mark> technologies & <mark>file systems</mark>;
  - hardware skills: tearing down <mark>embedded devices</mark>, id'ing components, reading <mark>schematics</mark> & <mark>datasheets</mark>, extracting & analyzing <mark>firmware</mark>;
  - other related interests: <mark>soldering</mark>, <mark>radio</mark>, <mark>network protocols</mark>, <mark>cryptography</mark>, <mark>security</mark>, <mark>DFIR</mark>, <mark>CI</mark>/<mark>CD</mark>/<mark>SSDLC</mark>, <mark>UX</mark>/<mark>design</mark>, <mark>scrum</mark>/<mark>kanban</mark>/<mark>agile</mark>.  




  **DISCLAIMER:** _**I am not affiliated in any way**_ with <mark>GNU/Linux</mark>'based <mark>ZorinOS</mark> distro.  




content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: IronOS
        link: https://github.com/Ralim/IronOS
        link_text: <u>IronOS by Ralim</u>
        sub_title: Official Maintainer
        caption: May, 2023 — currently
        additional_links:
          - title:  Contribution
            icon: fab fa-github
            url: https://github.com/Ralim/IronOS/pulls?q=is%3Apr+is%3Aclosed+author%3Aia
        quote: >
          Open Source Firmware for Soldering Hardware from Pine64, Miniware/Morningtools, and Sequre.
        description: |
          I joined this project with a couple of patches to improve the experience with my <mark>TS80P</mark>, but definitely have found way much more than just that, such as a lot of wonderful people & very interesting knowledge from them. Gained skills are (but not limited to):
          - getting familiar with <mark>STM</mark> _MCU_ family;
          - researching <mark>USB-C</mark> & <mark>QC</mark>/<mark>PD</mark> protocols;
          - <mark>FreeRTOS</mark> fundamentals;
          - <mark>Docker</mark> basics;
          - <mark>GitHub Actions</mark> under the hood to improve and maintain test & build pipelines;
          - _coding "tidiness"_, implemented & powered by <mark>clang-format</mark> for <mark>C</mark> & <mark>C++</mark> and by linters for <mark>Bash</mark> & <mark>Python</mark>;
          - a lot of _"glue scripting"_ between makefiles, <mark>JSON</mark> configs, <mark>Bash</mark>, <mark>Python</mark> & <mark>C</mark> & <mark>C++</mark> code;
          - minor refactoring of <mark>C</mark> & <mark>C++</mark> code & adding new features;
          - <mark>soft skills</mark>, to find & develop acceptable & compromise solutions for problems with the community together.  
            


  - title:
    layout: list
    content:
      - layout: left
        title: blisp
        link: https://github.com/PINE64/blisp
        link_text: blisp by PINE64
        sub_title: Contributor
        caption: December, 2024 — currently
        additional_links:
          - title:  PINE64/blisp
            icon: fab fa-github
            url: https://github.com/PINE64/blisp/pulls?q=is%3Apr+is%3Aclosed+author%3Aia
        quote: >
          Open Source Bouffalo Labs In-System-Programming tool to flash Bouffalo RISC-V MCUs.
        description: |
          While working on _IronOS_, I thought how else I could help and be useful with other related projects. So I got my hands on _blisp_ to use some of my knowledge there as well. In return I get more deep knowledge of _"tooling"_ using <mark>GitHub Actions</mark> and <mark>CMake</mark> build system.  
            


  - title:
    layout: list
    content:
      - layout: left
        title: HydraFW
        link: https://github.com/HydraBus/HydraFW
        link_text: <u>HydraFW by HydraBus</u>
        sub_title: Contributor
        caption: November, 2023 — currently
        additional_links:
          - title:  Contribution
            icon: fab fa-github
            url: https://github.com/hydrabus/hydrafw/pulls?q=is%3Apr+is%3Aclosed+author%3Aia
        quote: >
          Open Source Firmware for HydraBus — OSHW-based hardware hacking multitool.
        description: |
          I joined this project to improve `Makefile` since I was curious in a couple of aspects of _"tooling"_ the source code tree. But I ended up maintaining, refactoring & improving scripts in <mark>Bash</mark> & <mark>Python</mark>, bringing builds to <mark>GitHub Actions</mark> and getting familiar with <mark>ChibiOS</mark> to add a couple of features to the <mark>firmware</mark>.  
            


  - title:
    layout: list
    content:
      - layout: left
        title: femtocom
        link: https://github.com/ia/femtocom
        link_text: <u>ia/femtocom</u>
        sub_title: Developer & Maintainer
        caption: October, 2023 — currently
        additional_links:
          - title:  ia/femtocom
            icon: fab fa-github
            url: https://github.com/ia/femtocom/commits/main
        quote: >
          Simple Bash-based wrapper-like scripting app for picocom terminal app.
        description: |
          This is one of my little projects which make life easier. I wrote this <mark>Bash</mark> scripting app since I was getting tired of finding proper full path names for devices in `/dev` and dealing with serial port configuration for every device I have using serial console app manually to access it. Now after installing <mark>picocom</mark>, configuring <mark>udev</mark> & _INI_-like file for the script once, I can get access to all of my pre-configured devices as easy as `$ femtocom  DEVICE_ALIAS` when any of them are just plugged in.  

          <div style="text-align:center;"><a href="https://github.com/ia/femtocom" target="_blank"><img src="/images/femtocom.png" alt="femtocom"></a></div>  
            


  - title:
    layout: list
    content:
      - layout: left
        title: connect
        link: https://github.com/ia/connect
        link_text: <u>ia/connect</u>
        sub_title: Developer, Researcher & Maintainer
        caption: December, 2012 — currently
        additional_links:
          - title:  ia/connect
            icon: fab fa-github
            url: https://github.com/ia/connect/commits/master
        quote: >
          Tiny & portable fully cross-platform experimental network API library.
        description: |
          This is one of my oldest projects which I still try to keep afloat. The idea is to make `busybox`/`toybox`, but for network tools only, so `ping`, `netcat` or custom `tcpdump` utilities could be implemented using this library API with less then ten <mark>C</mark> calls for major operating systems including (but not limited to) <mark>GNU/Linux</mark>, <mark>FreeBSD</mark>, <mark>MacOS</mark>, <mark>QNX</mark>, <mark>Windows</mark>.  
          
          This project did help me a lot to learn many network basic technologies and _API_ such as (but not limited to):
          - foundations of ~~_OSI_ model~~ _**TCP/IP**_ **network model** & common network protocols;
          - common <mark>UNIX</mark> network _API_: <mark>BSD sockets</mark> (`socket`, `bind`, `listen`, `accept`, `recv`, `send`);
          - <mark>GNU/Linux</mark> network _API_: <mark>PF_PACKET</mark>/<mark>SOCK_RAW</mark>, <mark>epoll</mark>, <mark>skbuff</mark>, <mark>netlink</mark>, <mark>netfilter</mark>;
          - <mark>FreeBSD</mark>/<mark>MacOS</mark> network _API_: <mark>bpf</mark>, <mark>kqueue</mark>;
          - <mark>Windows</mark> network _API_: _Windows Sockets_ (<mark>WSA</mark>), <mark>NDIS</mark>;
          - `make` build systems for major operating systems including `nmake` for <mark>Windows</mark>;
          - rich <mark>C</mark> macros to write & build trully portable code without any modding from the side of a library _user_.  
            


  - title:
    layout: list
    content:
      - layout: left
        title: Battery Status
        link: https://wiki.gnome.org/Attic/BatteryStatus
        link_text: <u>BatteryStatus</u>
        sub_title: Developer, Designer & Maintainer
        caption: April, 2010 — May, 2011
        additional_links:
          - title:  Launchpad/BatteryStatus
            icon: fab fa-ubuntu
            url: https://launchpad.net/battery-status
        quote: >
          Graphical app to show all the details about a laptop battery in GTK-based GNU/Linux Desktop environments.
        description: |
          This was my very first solo Open Source project which I started from scratch and made it to the first official stable release. This allowed me to get a lot of experience with such things as <mark>Launchpad</mark> infrastructure, <mark>Bazaar</mark>, <mark>apt</mark> repos, <mark>deb</mark> packages, release cycles, <mark>GTK+</mark>, <mark>Python</mark>, <mark>PyGTK</mark>, <mark>D-Bus</mark> & <mark>UPower</mark>, <mark>UX</mark> & <mark>UI</mark> fundamental concepts.  


          Once the app has been tested & released, the project has been frozen since it's reached its goal and I just didn't have enough of time back then catching up with transitions like <mark>GTK2</mark> ⇒ <mark>GTK3</mark> & <mark>GNOME2</mark> ⇒ <mark>GNOME3</mark>.  

          <div style="text-align:center;"><a href="https://launchpad.net/battery-status" target="_blank"><img src="/images/batterystatus.png" alt="BatteryStatus"></a></div>  
            




  - title: Talks
    layout: list
    content:
      - layout: left
        title: OFF ZONE 24
        link: https://github.com/ia/talks/tree/main/offzone24
        link_text: <u>talks/offzone24</u>
        sub_title: Researcher, Author & Speaker
        caption: August 23, 2024
        additional_links:
          - title:  talk info
            icon: far fa-file-lines
            url: https://offzone.moscow/eng/program/ne-bezopasnost-ustroystv-interneta-veshchey-na-primere-nebolshogo-issledovaniya/
        quote: >
          Researching a multiprotocol USB modem, or Why “S” in IoT still stands for “Security”.
        description: |
          Despite unprecedented security incidents with such _IoT botnets_ as _Mirai_, there are still many devices whose security leaves much to be desired. And with a very particular set of skills and some luck, an unsafe device can be turned into an _"attack vector"_ for other devices. Sometimes it is not at all necessary to have hardcore skills in hardware analysis and rэvэrsэ engineering.  


          The talk was intended for a wide range of specialists interested in <mark>firmware security</mark>. It was overview of the modern device with the hints how to use common software tools to analyze <mark>GNU/Linux</mark>'based <mark>firmware</mark> for <mark>embedded hardware</mark>.  

          <div style="text-align:center;"><a href="https://github.com/ia/talks/blob/main/offzone24/OFF%20ZONE%2024%20-%20Ivan%20Zorin%20-%20Researching%20a%20multiprotocol%20usb%20modem.pdf" target="_blank"><img src="images/slide.png" alt="Intro Slide"></a></div>  
            




  - title: Contributions
    layout: list
    content:
      - layout: left
        title: CyanogenMod
        link: https://github.com/ia/android_system_vold/commit/62419cd8353d9b32e466ca2463c184d91b3879eb
        link_text: <u>system/vold</u>
        sub_title: System Engineer
        caption: July — October, 2015
        additional_links:
          - title:  XDA Post
            icon: fab fa-android
            url: https://xdaforums.com/t/rom-5-1-1-official-cyanogenmod-12-1.2958865/page-157#post-62554113
        quote: >
          system/vold patch for backward compatibility of Full Disk Encryption in CyanogenMod 12.1 with 3.x Linux kernel.
        description: |
          I had _Google Galaxy Nexus_ back then, and since I prefer to use my devices as long as they last, I had to build slightly custom <mark>AOSP</mark>'based CyanogenMod <mark>firmware</mark> for my device. But <mark>FDE</mark> didn't work properly. I had to trace & triage the root cause of the issue to fix it.  


          The problem did occur because in `system/vold` a system call (through `device-mapper` related _crypto API_ into the kernel space) wasn't compatible with out-of-dated _3.x Linux kernel_ since user space code in `system/vold` relied on more updated kernel versions. Therefore, implementing a workaround patch for `system/vold` with backward compatibility of _3.x Linux kernel_ did solve the issue.  
            


  - title:
    layout: list
    content:
      - layout: left
        title: Unity
        link: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/789979
        link_text: <u>Ubuntu/Unity</u>
        sub_title: Developer & QA Engineer
        caption: May — June, 2012
        additional_links:
          - title: Bazaar feature branch with the patch
            icon: fas fa-code-pull-request
            url: https://bazaar.launchpad.net/~iaz/unity/menubar-lp789979/revision/2384
        quote: >
          Patch for Ubuntu-based Unity Desktop Environment to show global menu all the time.
        description: |
          I used to use _Unity Desktop Environment_ back then, but there was a problem which was ruining the whole <mark>UX</mark> concept of _global menu_: the menu was fading away when wasn't active on focus. Without changing nor breaking anything else, I did utilize already existed options & values to add the ability for showing main menu always as an option.  


          My patch haven't been added to the upstream nor even considered for some reason, but _Unity_ core developers implemented this feature independently [_only three years later_](https://bugs.launchpad.net/ayatana-design/+bug/955193).  
            


  - title:
    layout: list
    content:
      - layout: left
        title: GNOME
        link: https://bugs.launchpad.net/ubuntu/+source/system-tools-backends/+bug/287134
        link_text: <u>Ubuntu/GNOME</u>
        sub_title: Security Researcher
        caption: October — November, 2008
        additional_links:
          - title: "USN-663-1: system-tools-backends regression"
            icon: fas fa-shield-halved
            url: https://ubuntu.com/security/notices/USN-663-1
        quote: >
          Security report about password hashing mechanism issue in GNOME.
        description: |
          I did discover the <mark>security</mark> issue: no matter how long a user password was, it was enough of the first 8 characters only of a password to log in. So I was helping _Ubuntu Security Team_ & [_Kees Cook_](https://github.com/kees) with everything I could back then to triage the root cause.  


          My original report did lead to the publication of the official _Ubuntu Security Notice_ [_USN-663-1_](https://ubuntu.com/security/notices/USN-663-1).  
            




  - title: A Little More About Me
    layout: text
    content: |
      Alongside my professional interests some of my other hobbies are:
      - Cinema, Video Games, Narrative Design & Dramaturgy;
      - Science Fiction & Cyberpunk;
      - Microelectronics;
      - Multitools & related EDC portable gear;
      - Communities of hackspaces, information technology/security conferences, meetups & events;
      - [_Free Software Ideology_](https://www.gnu.org/philosophy/free-sw.html);
      - Hardware Maintainance & Repair, heavily influenced by [_unimaginable contributions_](https://en.wikipedia.org/wiki/Right_to_repair) from [_Kyle Wiens_](https://kylewiens.com)' [_iFixit_](https://www.ifixit.com) & [_Louis Rossmann_](https://www.youtube.com/@rossmanngroup) to the society;
      - Digital Photography (without any post-processing) like this:

      <div style="text-align:center;"><img src="/images/rivercity.jpg" alt="Rivercity"></div>  
            




# Footer
footer_show_references: true
references_title: copyleft © 2025 (some rights reserved) // CC BY-NC-ND 4.0 unless stated otherwise.
footer_text: • copyleft © 2025 (some rights reserved) • Ivan Zorin • CC BY-NC-ND 4.0 unless stated otherwise •

# Build settings
remote_theme: ia/modern-resume-theme


sass:
  sass_dir: _sass
  style: compressed


plugins:
 - jekyll-seo-tag

