# Site
repository: ia/modern-resume-theme
favicon: images/cli.ico


# Content configuration version
version: 2


# Personal info
name: Ivan Zorin
title_tag: System Engineer
title: <ul><li>System Engineer</li><li>Open Source Developer</li><li>Independent Researcher</li><li>Community Manager</li><ul>
#title: |
#  System Engineer
#  Open Source Developer
#  Independent Researcher
#  Community Manager


#email: no-spam-please-no-please-no
#website: https://github.com/ia/modern-resume-theme


# Dark Mode (true/false/never)
darkmode: false


# Social links
# github_username:
# flickr_username:
# instagram_username:
# linkedin_username: ivzin


# font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
additional_links:
- title: GitHub
  icon: fab fa-github
  url: https://github.com/ia
#- title: CV
#  icon: fas fa-file-invoice
#  url: https://ia.github.io/cv
#- title: LinkedIn
#  icon: fab fa-linkedin-in
#  url: https://linkedin.com/in/ivzin
#- title: Blog
#  icon: fas fa-i-cursor
#  url: https://ia.github.io/log/
- title: HomeLab
  icon: fas fa-microchip
  url: https://h0melab.github.io


# About Section
# about_title: About Me
#?about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, friend. I'm just a regular average techie, but very curious one and this is my resume, community edition:  




  - natural languages: <mark>English</mark>, <mark>Russian</mark>;
  - programming languages: <mark>Bash</mark>, <mark>C</mark>/<mark>C++</mark>, <mark>Python</mark>;
  - operating systems: experience of tampering with <mark>Windows</mark>, <mark>MacOS</mark>, <mark>FreeBSD</mark>, <mark>ThreadX</mark>, <mark>QNX</mark>, <mark>Android</mark>, <mark>GNU/Linux</mark>;
  - server management: basic knowledge of how to deploy, configure & maintain <mark>Nginx</mark>, <mark>Samba</mark>, <mark>OpenVPN</mark>, <mark>OpenSSH</mark>, <mark>TFTP</mark>;
  - web: minimal level of <mark>HTML</mark>/<mark>CSS</mark>/<mark>JavaScript</mark> and <mark>Jekyll</mark>/<mark>Liquid</mark>/<mark>YAML</mark> to make clean, lightweight & elegant static sites;
  - testing: deep <mark>SDET</mark>/<mark>QA</mark> automation experience by developing test tools and making custom hardware stands to test & verify system software;
  - development tools: <mark>GCC</mark> & <mark>LLVM</mark> <mark>toolchains</mark> usage for cross-compilation, porting and code sanitization;
  - system skills: <mark>POSIX</mark>, network programming (<mark>BSD sockets</mark> & <mark>WinSock</mark>) and packet routing, storage technologies & <mark>filesystems</mark>;
  - hardware skills: tearing down <mark>embedded devices</mark>, id'ying components, reading <mark>schematics</mark> & <mark>datasheets</mark>, extracting & analyzing <mark>firmware</mark>;
  - other related interests: <mark>soldering</mark>, <mark>network protocols</mark>, <mark>cryptography</mark>, <mark>security</mark>, <mark>DFIR</mark>, <mark>CI</mark>/<mark>CD</mark>, <mark>UX</mark>/<mark>design</mark>, <mark>scrum</mark>/<mark>kanban</mark>/<mark>agile</mark>.  




  **DISCLAIMER:** _**I am not affiliated in any way**_ with <mark>GNU/Linux</mark>'based <mark>ZorinOS</mark> distro.  




content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: IronOS
        link: https://github.com/Ralim/IronOS
        link_text: IronOS by Ralim
        sub_title: Official Maintainer
        caption: Currently
        additional_links:
          - title:  Contribution
            icon: fab fa-github
            url: https://github.com/Ralim/IronOS/pulls?q=is%3Apr+is%3Aclosed+author%3Aia
        quote: >
          Open Source Firmware for Smart Soldering Irons from Pine64, Miniware/Morningtools and Sequre.
        description: |
          I joined this project with a couple of patches to improve the experience with my <mark>TS80P</mark>, but definitely have found way much more than just that, such as a lot of wonderful people & very interesting knowledge from them. Gained skills are (but not limited to):
          - getting familiar with <mark>STM</mark>'based MCUs;
          - researching <mark>USB-C</mark> & <mark>QC</mark>/<mark>PD</mark> protocols;
          - <mark>FreeRTOS</mark> fundamentals;
          - <mark>Docker</mark> basics;
          - <mark>GitHub Actions</mark> under the hood;
          - _coding "tidiness"_, implemented & powered by <mark>clang-format</mark> for <mark>C</mark>/<mark>C++</mark> and by linters for <mark>Bash</mark> & <mark>Python</mark>;
          - a lot of _"glue scripting"_ between makefiles, <mark>JSON</mark> configs, <mark>Bash</mark>, <mark>Python</mark> & <mark>C</mark>/<mark>C++</mark> code;
          - minor refactoring of <mark>C</mark>/<mark>C++</mark> code & adding new features;
          - <mark>soft skills</mark>, to find & develop acceptable & compromise solutions for problems with the community together.  
            




  - title:
    layout: list
    content:
      - layout: left
        title: HydraFW
        link: https://github.com/HydraBus/HydraFW
        link_text: HydraFW by HydraBus
        sub_title: Contributor
        caption: Currently
        additional_links:
          - title:  Contribution
            icon: fab fa-github
            url: https://github.com/hydrabus/hydrafw/pulls?q=is%3Apr+is%3Aclosed+author%3Aia
        quote: >
          Open Source Firmware for HydraBus — OSHW-based hardware hacking multitool.
        description: |
          I joined this project to improve <mark>Makefile</mark> since I was curious in a couple of aspects of _"tooling"_ the source code tree. But I ended up maintaining, refactoring & improving scripts in <mark>Bash</mark> & <mark>Python</mark>, bringing builds to <mark>GitHub Actions</mark> and getting familiar with <mark>ChibiOS</mark> to add a couple of features to the <mark>firmware</mark>.  
            




  - title:
    layout: list
    content:
      - layout: left
        title: femtocom
        link: https://github.com/ia/femtocom
        link_text: ia/femtocom
        sub_title: Developer & Maintainer
        caption: Currently
        additional_links:
          - title:  ia/femtocom
            icon: fab fa-github
            url: https://github.com/ia/femtocom/commits/main
        quote: >
          Simple Bash-based wrapper-like scripting app for picocom terminal app.
        description: |
          This is one of my little projects which make life easier. I wrote this <mark>Bash</mark> scripting app since I was getting tired of finding proper full path names for devices in <mark>/dev</mark> and dealing with serial port configuration for every device I have using serial console app manually to access it. Now after installing <mark>picocom</mark>, configuring <mark>udev</mark> & _INI_-like file for the script once, I can get access to all of my pre-configured devices as easy as `$ femtocom  DEVICE_ALIAS` when any of them are just plugged in.

          <div style="text-align:center;"><img src="/images/femtocom.png" alt="femtocom"></div>
            




  - title: Past Contributions
    layout: list
    content:
      - layout: left
        title: Battery Status
        link: https://wiki.gnome.org/Attic/BatteryStatus
        link_text: BatteryStatus
        sub_title: Developer & Maintainer
        caption: April 2010 — May 2011
        additional_links:
          - title:  Launchpad/BatteryStatus
            icon: fab fa-ubuntu
            url: https://launchpad.net/battery-status
        quote: >
          Graphical app to show all the details about a laptop battery in GTK-based GNU/Linux Desktop environments.
        description: |
          This was my very first solo Open Source project which I started from scratch and made it to the first official stable release. This allowed me to get a lot of experience with such things as <mark>Launchpad</mark> infrastructure, <mark>Bazaar</mark> SCM, <mark>apt</mark> repos, <mark>deb</mark> packages, release cycles, <mark>GTK+</mark>, <mark>Python</mark>, <mark>PyGTK</mark>, <mark>DBus</mark> & <mark>UPower</mark>, <mark>UX</mark> & <mark>UI</mark> fundamental concepts.  


          Once the app has been tested & released, the project has been frozen since it's reached its goal and I just didn't have enough of time back then catching up with transitions like GTK2⇒GTK3 & GNOME2⇒GNOME3.  

          <div style="text-align:center;"><img src="/images/batterystatus.png" alt="BatteryStatus"></div>


  - title: A Little More About Me
    layout: text
    content: |
      Alongside my professional interests some of my other hobbies are:
      - Cinema, Video Games, Narrative Design & Dramaturgy;
      - Science Fiction & Cyberpunk;
      - Microelectronics;
      - Multitools & related EDC portable gear;
      - Hardware Maintainance & Repair, heavily influenced by [unimaginable contributions](https://en.wikipedia.org/wiki/Right_to_repair) from [Kyle Wiens](https://kylewiens.com)' [iFixit](https://www.ifixit.com) & [Louis Rossmann](https://www.youtube.com/@rossmanngroup) to the society;
      - Digital Photography (without any post-processing) like this:

      <div style="text-align:center;"><img src="/images/rivercity.jpg" alt="Rivercity"></div>


# Footer
footer_show_references: true
references_title: copyleft © 2024 (some rights reserved) // CC BY-NC-ND 4.0 unless stated otherwise.


# Build settings
remote_theme: ia/modern-resume-theme


sass:
  sass_dir: _sass
  style: compressed


plugins:
 - jekyll-seo-tag

